name: guardian_flutter
description: GUARDIAN - flutter version

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: 1.0.3

  flutter_svg: 0.22.0

  flutter_reaction_button: ^1.0.8

#  mapbox_gl: 0.12.0

  # -7.0.1
  geolocator: 7.0.3

  rflutter_alert: 2.0.2

  # -0.13.0
  http: 0.13.3

  provider: ^5.0.0

  # -0.17.0
  intl: 0.17.0

  socket_io_client: 2.0.0-beta.4-nullsafety.0

  flutter_simple_dependency_injection: 2.0.0

#  flutter_local_notifications: 5.0.0+4

  flutter_custom_tabs: 1.0.3

  chopper: 4.0.1

  # -4.0.1
  json_annotation: 4.0.1

  # -1.0.0
  logging: 1.0.1

  device_info: 2.0.2

#  flutter_facebook_login: ^3.0.0

  # -1.0.0
  firebase_auth: 1.2.0

  # -5.0.0
  google_sign_in: 5.0.4

  get_mac: ^0.0.1

  firebase_analytics: any

  # -9.0.0
  firebase_messaging: 10.0.0

  # -1.0.0
  firebase_core: 1.2.0

  font_awesome_flutter: ^9.0.0

  # -0.8.0
  camera: 0.8.1+1

  # -0.7.2
  image_picker: 0.8.0

  path: ^1.8.0

  path_provider: 2.0.2

  # -2.0.0
  hive: 2.0.4

  qr_flutter: ^4.0.0

  flip_card: ^0.5.0

  image_crop: 0.4.0

  flutter_swiper: ^1.1.6

  flutter_datetime_picker: 1.5.1

  # -2.0.1
  google_maps_flutter: ^2.0.6

  google_geocoding: 0.2.0

  textfield_tags: 1.2.0

  network_to_file_image: 2.3.8

  transparent_image: ^2.0.0

  flutter_spinkit: ^5.0.0

  email_validator: ^2.0.1

  popup_menu: ^1.0.5

  flutter_google_places: 0.3.0

  google_maps_webservice: 0.0.20-nullsafety.3

  threading: ^0.0.10

  video_player: ^2.1.12

  address_search_field: ^4.0.1

  validators: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # -1.12.2
  build_runner: 2.0.4

  chopper_generator: 4.0.1

  # -4.1.0
  json_serializable: 4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/buttons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
